# Generated by Django 4.2 on 2026-03-22 08:56

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "course_id",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("course_name", models.CharField(db_index=True, max_length=200)),
                ("course_short_name", models.CharField(max_length=50)),
                ("course_category", models.CharField(db_index=True, max_length=100)),
                (
                    "course_duration",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "duration_unit",
                    models.CharField(
                        choices=[
                            ("DAY", "Days"),
                            ("WEEK", "Weeks"),
                            ("MONTH", "Months"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "course_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency_code", models.CharField(max_length=3)),
                (
                    "course_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=30)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("STATUS_CHANGE", "Status Change"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user", models.CharField(max_length=50)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["course_name"], name="courses_cou_course__238746_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["course_category"], name="courses_cou_course__b2b4d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["course_status"], name="courses_cou_course__58df85_idx"
            ),
        ),
    ]
