# Generated by Django 4.2 on 2026-03-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NumberingSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_name", models.CharField(max_length=50, unique=True)),
                ("prefix", models.CharField(max_length=10)),
                ("current_number", models.IntegerField(default=0)),
                ("padding", models.IntegerField(default=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
